language: csharp
install:
  - sudo apt-get install -y git make
script:    
  - git config --global user.email "hello@bye.com"
  - git config --global user.name  "Hello Bye"
  - make paket.restore
  - make test
mono:
  - 4.6.0